### ISSUE TITLE
після сортування у вас виходить що помінялися суми стовбців - ми всього навсього мали міняти стовбці місцями а сума їх має залишитися незмінною

### ISSUE THREAD

**Issue by albussiverus** [tolstopiatova/hilel_homework#2]
https://github.com/tolstopiatova/hilel_homework/blob/9e09ea7b6ace6f8a350a9b8ab98e0364f155c05b/12th_lesson_1.py#L29

Після сотрування у вас виходить інші суми стовбців - як таке могло б вийти?
<img width="474" alt="image" src="https://github.com/tolstopiatova/hilel_homework/assets/142038191/74d97c68-49a0-4822-8ce3-bc8ff2d6c3be">

В завадні проситься застосування  алгоритму сотування бульбашкою

**Comment by tolstopiatova** [comment]
виправила
